core: psa-adac: fix compilation issue due to static_buffer_msg.h
Fix the following errors:
core/lib/psa-adac/transport_layer/transports/static_buffer_msg.h:16:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
   16 | int psa_adac_static_buffer_msg_release();
      | ^~~
core/lib/psa-adac/transport_layer/transports/static_buffer_msg.h:18:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
   18 | request_packet_t *psa_adac_static_buffer_msg_get_request();
      | ^~~~~~~~~~~~~~~~
core/lib/psa-adac/transport_layer/transports/static_buffer_msg.h:19:1: error: function declaration isn’t a prototype [-Werror=strict-prototypes]
   19 | response_packet_t *psa_adac_static_buffer_msg_get_response();

Signed-off-by: Amelie Delaunay <amelie.delaunay@foss.st.com>
Change-Id: I918090aba2c0ebc3153f54093c8d9a760c08c869
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/433584
Domain-Review: Yann GAUTIER <yann.gautier@foss.st.com>
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
Reviewed-by: Thomas BOURGOIN <thomas.bourgoin@foss.st.com>