drivers: scmi-msg: move static_assert out of the case statement
static_assert in a case produce this error at compilation time:
error: a label can only be part of a statement and a declaration is not
a statement
   59 | #define static_assert _Static_assert
      |                       ^~~~~~~~~~~~~~

Move them out of the function.

Fixes: 47a26c739bc3 ("drivers: scmi-msg: specific OSTLv4/v5 duty-cycle/round_rate messages")
Signed-off-by: Valentin Caron <valentin.caron@foss.st.com>
Change-Id: I0ce0f4394c3a795b5d4a574cc2be2f61a4db693f
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/435935
Domain-Review: Thomas BOURGOIN <thomas.bourgoin@foss.st.com>
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
Reviewed-by: Thomas BOURGOIN <thomas.bourgoin@foss.st.com>