core: psa-adac: fix adac-crypto.c compilation
When PSA_ADAC_ED25519 and/or PSA_ADAC_ED448 are defined, it raises the
following build error:
core/lib/psa-adac/psa-adac/core/src/adac_crypto.c:71:9: error: ‘ext_words’ undeclared (first use in this function)
   71 |         ext_words = certificate->header.extensions_bytes;
      |         ^~~~~~~~~
Fix the issue using ext_bytes instead of ext_words, as used elsewhere.

Ignore code indent error on this patch, code indent follows the
indent style of the file.

Signed-off-by: Amelie Delaunay <amelie.delaunay@foss.st.com>
Change-Id: I1935cdec1c3554565517d068c2daeccc495b7e21
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/433582
Domain-Review: Yann GAUTIER <yann.gautier@foss.st.com>
ACI: CIBUILD <MDG-smet-aci-builds@list.st.com>
Reviewed-by: Thomas BOURGOIN <thomas.bourgoin@foss.st.com>