scripts: sign_rproc_fw: fix cryptography import
On windows PC following error is reported running the script:

from cryptography.hazmat.primitives.ciphers.aead import utils
ImportError: cannot import name 'utils' from
'cryptography.hazmat.primitives.ciphers.aead'

Fix the import to be compliant with windows PC.

Fixes: 41190c54a0f5 ("scripts: sign_rproc_fw: Add support for AES CBC encryption")

Signed-off-by: Arnaud Pouliquen <arnaud.pouliquen@foss.st.com>
Change-Id: I1bc583191abd755b554f4a8a3080ec1d360a3a85
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/optee_os/+/420224
Reviewed-by: Arnaud POULIQUEN <arnaud.pouliquen@st.com>
Domain-Review: Arnaud POULIQUEN <arnaud.pouliquen@st.com>
Tested-by: Arnaud POULIQUEN <arnaud.pouliquen@st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>
Reviewed-by: Thomas BOURGOIN <thomas.bourgoin@foss.st.com>