module: scmi_clock: move static_assert out of the case statement
static_assert in a case produce this error at compilation time:
error: a label can only be part of a statement and a declaration is not
a statement
   59 | #define static_assert _Static_assert
      |                       ^~~~~~~~~~~~~~

Move them out of the function.

Fixes: 3042affbb6de ("module: scmi_clock: specific OSTLv4/v5 duty-cycle/round_rate messages")
Signed-off-by: Valentin Caron <valentin.caron@foss.st.com>
Change-Id: Ie10a9f00f628fbf02b0062141a60edda1042da87
Reviewed-on: https://gerrit.st.com/c/mpu/oe/optee/SCP-firmware/+/435926
Reviewed-by: Gatien CHEVALLIER <gatien.chevallier@st.com>
Domain-Review: Gatien CHEVALLIER <gatien.chevallier@st.com>
ACI: CITOOLS <MDG-smet-aci-reviews@list.st.com>